[workspace]
members = [
  # "examples/rust/battleship",
  "examples/rust/battleship/core",
  "examples/rust/battleship/web/client",
  # "examples/rust/battleship/web/server",
  "risc0/zkvm/sdk/rust/core",
  "risc0/zkvm/sdk/rust/serde",
]
